# Generated by Django 5.1 on 2024-09-02 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_userprofile"),
    ]

    operations = []
