# Generated by Django 5.1 on 2024-09-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0004_weekplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="weekplan",
            name="name",
            field=models.CharField(default="Unnamed Plan", max_length=100),
        ),
    ]
