# Generated by Django 5.1 on 2024-09-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0005_weekplan_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="weekplan",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
